name: Pull Request Review Status Label
description: GitHub Action that labels pull requests depending on the review status.
author: João Brilhante

branding:
  icon: tag
  color: blue

inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: "1000"

outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
